# Generated by Django 4.2.2 on 2023-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_authornew'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='authorNew',
            field=models.CharField(max_length=30),
        ),
    ]
