# Generated by Django 4.2.2 on 2023-07-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_authornew'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
    ]
